"""vehicle type/wheeler registry tables + vehicle acquisition fields

Revision ID: a1b2c3d4e5f6
Revises: 76ee7e932fab
Create Date: 2026-08-06 15:10:00.000000

Hand-written instead of autogenerated: this database has pre-existing
drift (several columns exist in the db that aren't in the current model
classes - old file-upload fields etc.) that `flask db migrate` picks up
as "removed columns" and would DROP if applied blindly. This migration
only does the two things actually needed for this change: create the
vehicle_types/wheelers registry tables (Vehicle Types & Wheelers page),
and add the new Vehicle acquisition columns. Everything else is left
untouched.
"""
from alembic import op
import sqlalchemy as sa


revision = 'a1b2c3d4e5f6'
down_revision = '76ee7e932fab'
branch_labels = None
depends_on = None


def upgrade():
    # This local dev db already had vehicle_types/wheelers created out of
    # band from an earlier attempt at this same feature - guard so this
    # migration is also safe to run fresh (e.g. on first deploy elsewhere).
    bind = op.get_bind()
    existing_tables = sa.inspect(bind).get_table_names()

    if 'vehicle_types' not in existing_tables:
        op.create_table(
            'vehicle_types',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name'),
        )
    if 'wheelers' not in existing_tables:
        op.create_table(
            'wheelers',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name'),
        )

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('make', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('leased', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registration_name', sa.String(length=100), nullable=True))


def downgrade():
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('registration_name')
        batch_op.drop_column('leased')
        batch_op.drop_column('value')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('make')
        batch_op.drop_column('model_year')
    op.drop_table('wheelers')
    op.drop_table('vehicle_types')
